services:
  proxylotl:
    container_name: proxylotl
    image: opisek/proxylotl:latest
    volumes:
      - /srv/proxylotl/config.yml:/app/config.yml:ro
      - /srv/proxylotl/scripts:/app/scripts:ro
      - /srv/proxylotl/status:/app/status
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    network_mode: host
    environment:
      - CONFIG=./config.yml
      - PORT=25565
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile