services:
  proxelot:
    container_name: proxelot
    image: opisek/proxelot:latest
    volumes:
      - /srv/proxelot/scripts:/app/scripts:ro
      - /srv/proxelot/config.yml:/app/config.yml:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    network_mode: host
    environment:
      - CONFIG=./config.yml
      - PORT=25565
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile